package com.salahalkmali.contactsapp.data;

/**
 * @author salahalkmali Philip Asare
 * @version 1.0
 * This class represent a a Contact with properties Id, Name , Telephone Number, Email and  Address(Location).
 */

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;


@Entity(tableName = "contact_table")
public class Contact {


    /**
     * Contact id, generated by auto increment. Unique id to be used as primary key in database.
     */
    @PrimaryKey(autoGenerate = true)
    @NonNull
    @ColumnInfo(name = "contact_id")
    int mID;

    /**
     * Coantact name
     */
    @NonNull
    @ColumnInfo(name = "contact_name")
    String mName;
    /**
     * Contact telephone/Mobile Number
     */
    @NonNull
    @ColumnInfo(name = "contact_tel")
    String mTelephone;
    /**
     * Contact emain Address
     */
    @ColumnInfo(name = "contact_email")
    String mEmail;


    public Contact(){}



    /**
     *Create a Contact object from a constructor with contact id, name, telephone and email
     * @param id {@link Contact#mID}
     * @param name  {@link Contact#mName}
     * @param telephone  {@link Contact#mTelephone}
     * @param email  {@link Contact#mEmail}
     */
    @Ignore
    public Contact(int id, String name, String telephone, String email) {
        this.mID = id;
        this.mName = name;
        this.mTelephone = telephone;
        this.mEmail = email;
    }


    /**
     *Create a Contact object from a constructor with contact id, name and telephone.
     * @param id {@link Contact#mID}
     * @param name  {@link Contact#mName}
     * @param telephone  {@link Contact#mTelephone}
     */
    @Ignore
    public Contact(int id, String name, String telephone) {
        this.mID = id;
        this.mName = name;
        this.mTelephone = telephone;
    }



    /**
     *Create a Contact object from a constructor with contact name, telephone and email
     * @param name  {@link Contact#mName}
     * @param telephone  {@link Contact#mTelephone}
     * @param email  {@link Contact#mEmail}
     */
    @Ignore
    public Contact(String name, String telephone, String email) {
        this.mName = name;
        this.mTelephone = telephone;
        this.mEmail = email;
    }


    /**
     *Create a Contact object from a constructor with contact name and telephone.
     * @param name  {@link Contact#mName}
     * @param telephone  {@link Contact#mTelephone}
     */
    @Ignore
    public Contact(String name, String telephone) {
        this.mName = name;
        this.mTelephone = telephone;
    }

    /**
     * Sets contact email address
     * @return {@link Contact#mEmail}
     */
    public String getMEmail() {
        return this.mEmail;
    }

    /**
     *
     * @param mEmail contact emaial address
     */
    public void setMemail(String mEmail) {
        this.mEmail = mEmail;
    }

    /**
     *
     * @return {@link Contact#mName} Conatact name
     */
    public String getMname() {
        return this.mName;
    }

    /**
     *
     * @param mName {@link Contact#mName}
     */
    public void setMname(String mName) {
        this.mName = mName;
    }

    /**
     *
     * @return {@link Contact#mTelephone}
     */
    public String getMtelephone() {
        return this.mTelephone;
    }

    /**
     *
     * @param mTelephone {@link Contact#mTelephone}
     */
    public void setMtelephone(String mTelephone) {
        this.mTelephone = mTelephone;
    }

    /**
     * Returns contact Id.
     * @return int {@link Contact#mID}
     */
    public int getMid() {
        return this.mID;
    }

}
